### PR TITLE
Rewrite Makefile to support unified build as part of husky subprojects

### PR DESCRIPTION
**Pull request by spanevin**
Corresponding PR for huskybse: https://github.com/huskyproject/huskybse/pull/11

### CODE REVIEW

**Review by dukelsky — CHANGES_REQUESTED** [review]
The same comments here, as for `bsopack`.

**Comment by dukelsky** [comment]
Please test that the `hpucode` works somehow after your changes in the build.

**Comment by spanevin** [comment]
> Please test that the `hpucode` works somehow after your changes in the build.

What does "somehow" mean? It shows usage message, is it enough? :)

**Comment by dukelsky** [comment]
> > Please test that the `hpucode` works somehow after your changes in the build.
> 
> What does "somehow" mean? It shows usage message, is it enough? :)

Yes.

**Review by dukelsky — APPROVED** [review]

**Pull request merged**
